### ISSUE TITLE
Deploy new version to npm

### ISSUE THREAD

**Issue by cgorman** [ImagingDataCommons/dicom-microscopy-viewer#98]
@hackermd the npm repo is currently tied to your account. Can you either make a deployment for 0.45.0 or somehow migrate it to an IDC account or something?

**Comment by fedorov** [comment]
For the sake of completeness, this is the npm package in question: https://www.npmjs.com/package/dicom-microscopy-viewer.

@hackermd this issue is in the critical path for the upcoming IDC release. We have a dataset that we will not be able to release until a visualization issue is fixed, and to test if it was fixed we need to upgrade this package.

**Comment by hackermd** [comment]
@cgorman @fedorov I published the 0.45.0 version: https://www.npmjs.com/package/dicom-microscopy-viewer/v/0.45.0
